import { withEdgeSpec } from "lib/with-edge-spec"
import { z } from "zod"

export default withEdgeSpec({
  methods: ["GET"],
  queryParams: z.object({}),
  jsonResponse: z.object({
    id: z.number(),
    login: z.string(),
    node_id: z.string(),
    avatar_url: z.string().url(),
    gravatar_id: z.string(),
    url: z.string().url(),
    html_url: z.string().url(),
    followers_url: z.string().url(),
    following_url: z.string().url(),
    gists_url: z.string().url(),
    starred_url: z.string().url(),
    subscriptions_url: z.string().url(),
    organizations_url: z.string().url(),
    repos_url: z.string().url(),
    events_url: z.string().url(),
    received_events_url: z.string().url(),
    type: z.string(),
    site_admin: z.boolean(),
    name: z.string().nullable(),
    company: z.string().nullable(),
    blog: z.string().url().nullable(),
    location: z.string().nullable(),
    email: z.string().email().nullable(),
    hireable: z.boolean().nullable(),
    bio: z.string().nullable(),
    twitter_username: z.string().nullable(),
    public_repos: z.number(),
    public_gists: z.number(),
    followers: z.number(),
    following: z.number(),
    created_at: z.string(),
    updated_at: z.string(),
  }),
})(async (req, ctx) => {
  return ctx.json({
    id: 1,
    login: "octocat",
    node_id: "MDQ6VXNlcjE=",
    avatar_url: "https://avatars.githubusercontent.com/u/1?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/octocat",
    html_url: "https://github.com/octocat",
    followers_url: "https://api.github.com/users/octocat/followers",
    following_url:
      "https://api.github.com/users/octocat/following{/other_user}",
    gists_url: "https://api.github.com/users/octocat/gists{/gist_id}",
    starred_url: "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/octocat/subscriptions",
    organizations_url: "https://api.github.com/users/octocat/orgs",
    repos_url: "https://api.github.com/users/octocat/repos",
    events_url: "https://api.github.com/users/octocat/events{/privacy}",
    received_events_url: "https://api.github.com/users/octocat/received_events",
    type: "User",
    site_admin: false,
    name: "The Octocat",
    company: "GitHub",
    blog: "https://github.blog",
    location: "San Francisco",
    email: "octocat@github.com",
    hireable: true,
    bio: "A mysterious octocat GitHub mascot",
    twitter_username: "octocat",
    public_repos: 8,
    public_gists: 8,
    followers: 2000,
    following: 5,
    created_at: "2008-01-14T04:33:35Z",
    updated_at: "2021-05-20T11:34:15Z",
  })
})
